### ISSUE TITLE
I want this to exist!!!

### ISSUE THREAD

**Issue by deltaepsilon** [iann0036/cloud9-sync#1]
This isn't an issue... it's a 🙌

I want to use Cloud9 so badly...  but I also NEED to use VSCode. I do a ton of pair-programming, and being able to rock and roll on Cloud9 would be amazing.

But none of us want to use any editor other than VSCode.

What's your outlook on this project? I was so excited to see it in the Extensions search results.

**Comment by iann0036** [comment]
Hey Chris 👋

Thanks for reaching out. I do intend to work on this project until it's ready for production use. My main focus points at the moment are the synchronisation system (about to rewrite to allow remote file browsing) and the live edit stability.

If you have any features you'd like to see, or functionality you can't live without, please let me know and I'll do my best to work it in.

**Comment by deltaepsilon** [comment]
I'm just going to sit tight and wait for my opportunity to give this a test drive.

It may be a while... but this is such a big gap right now for pair programming and just computer-switchers in general. I would love to get all of my stuff on Cloud9 and never be tied to a machine again.
