### ISSUE TITLE
Issue with connecting to Environment

### ISSUE THREAD

**Issue by harunkK** [iann0036/cloud9-sync#15]
Hi,
First of all thank you for this great tool, I'm looking forward to start coding on Vs Code :D
I entered all the required credentials, and it does refresh the environment list, bringing me the list properly.
However when I try to connect to my environment, it gives authorization error.

User: arn:aws:iam:::user/ is not authorized to perform: cloud9:CreateEnvironmentToken on resource: XXX with an explicit deny

Any idea where I did wrong?

Thanks

**Comment by iann0036** [comment]
Hi there,

Is it possible that the environment was created as a user other than the one you authorised in VS Code? If so, you may need to share the environment (https://docs.aws.amazon.com/cloud9/latest/user-guide/share-environment.html#share-environment-invite-user) with that user from the owners context.

**Comment by harunkK** [comment]
Amazing, it worked wonderful!

Thank you:_
