### ISSUE TITLE
Disconnected from AWS Cloud9 environment

### ISSUE THREAD

**Issue by allgf27** [iann0036/cloud9-sync#21]
Hi
When I try to connect to the environment, I get the following error:

Disconnected from AWS Cloud9 environment
Error connecting with AWS Cloud9 environment

What should I do in this case?

**Comment by iann0036** [comment]
Can you see anything particularly interesting in the console (Help > Toggle Developer Tools > Console)?

Sanitise anything sensitive!

**Comment by allgf27** [comment]
Basically
```
sending
--GOT MESSAGE--
```
are continued, but found some errors:
```
Error: EEXIST: Extension API already defined for ping \ n ...
Error: ENOENT: no such file or directory, lstat '/home/ec2-user/environment/.eslintrc'\n ...
Error: Command failed: sudo chown ec2-user -R / usr / local / rvm / gems \ nchown: can not access / usr / local / rvm / gems': No such file or directory \ n \ n ...
Error: Command failed: node -e log (Date.now ()) \ n [eval]: 1 \ nlog (Date.now ()) \ n ^ \ n \ nReferenceError: log is not defined \ n ...
```

**Comment by iann0036** [comment]
Hmm, annoying. I believe the above errors are normal behaviour.

It does seem to be connecting to the environment WebSocket and doing call / response. Were you prompted for sync strategy (None, Download Only, Bi-directional)?

**Comment by allgf27** [comment]
No
Where can I set sync strategy?

**Comment by allgf27** [comment]
Once I left VSCode and started again, I was able to connect 
(displayed next to the environment name (connected))

**Comment by iann0036** [comment]
Huh. Very weird.

I'll have to look into that. Thanks for raising though!
