### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yoshiaki35** [iann0036/cloud9-sync#26]
- Issue Type: `Performance`
- Extension Name: `live-share-for-aws-cloud9`
- Extension Version: `0.10.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\yoshiaki35\iann0036.live-share-for-aws-cloud9-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by iann0036** [comment]
Hi @yoshiaki35,

Thanks for raising!

Would you mind attaching the highlighted cpuprofile file (or send it to cloud9@ian.mn) so I can analyze your issue?
