### ISSUE TITLE
Not creating new files or new folders

### ISSUE THREAD

**Issue by igorjunio2015** [iann0036/cloud9-sync#27]
When trying to create anything through VSCODE, you just don't.
For this to work I have to go through the browser and create.

![image](https://user-images.githubusercontent.com/53827311/73572612-fe6ec980-444f-11ea-8635-0c57ac4fd0a7.png)

![image](https://user-images.githubusercontent.com/53827311/73572620-03cc1400-4450-11ea-9951-cc4ab6de0ea0.png)

Console log:

![image](https://user-images.githubusercontent.com/53827311/73573277-be104b00-4451-11ea-918c-bf2caf2fbc05.png)

Error message VSCODE:

![image](https://user-images.githubusercontent.com/53827311/73573709-ce74f580-4452-11ea-9bdf-dd8a02837d6b.png)

**Comment by iann0036** [comment]
Hi @igorjunio2015 ,

Is this on an initial sync or when you create files after the fact?
Are the files in a subdirectory or does creating files at the root level work?
Does this work in the non-"Add to your workspace" mode with a new environment?

**Comment by igorjunio2015** [comment]
So, I did the synchronization and added the environment.

However, when I try to create a file or folder, either in the root folder or in subfolders, it doesn't.

And even creating a new environment, the creation of file and folder by VISUAL STUDIO CODE does not work.

**Comment by iann0036** [comment]
Hey @igorjunio2015,

Just wanted to check, does the updates from your comment here (https://github.com/iann0036/cloud9-sync/issues/24#issuecomment-581173977) solve this specific issue or are they different and you still have this issue?

**Comment by igorjunio2015** [comment]
That problem was related to the TERMINAL, and it was solved.

Now to create files and folders in my environment that is not working.

**Comment by iann0036** [comment]
Could you paste the full console log here or send it through to cloud9sync@ian.mn ?

I'll probably need it to reconstruct the sequence of events.

**Comment by igorjunio2015** [comment]
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10035,"seq":20039,"d":["call","ping","ping",["serverTime",{"$":32}]]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20039,"seq":10036,"d":[32,null,{"serverTime":2}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 3
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10036,"seq":20040,"d":["stat","/gobarber/src/Teste.js",{},{"$":91}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20040,"seq":10037,"d":[91,{"stack":"22282: 2069: Error: ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/Teste.js'\n    at Error (native)","code":"ENOENT","message":"ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/Teste.js'"}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10037,"seq":20041,"d":["call","ping","ping",["serverTime",{"$":32}]]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20041,"seq":10038,"d":[32,null,{"serverTime":2}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10038,"seq":20042,"d":["stat","/gobarber/src",{},{"$":91}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20042,"seq":10039,"d":[91,null,{"name":"src","size":4096,"mtime":1580494049457,"ctime":1580494049457,"mime":"inode/directory"}]}
console.ts:137 [Extension Host] LISTDIR RESPONSE
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host]% {statusCode: 200, body: "ENOENT: no such file or directory, stat '/home/ubuntu/environment/gobarber/src/Teste.js/'↵", headers: {…}, request: {…}}
console.ts:137 [Extension Host] ENOENT: no such file or directory, stat '/home/ubuntu/environment/gobarber/src/Teste.js/'
console.ts:137 [Extension Host] LISTDIR RESPONSE
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host]% {statusCode: 200, body: "[↵  {"name":"app.js","size":325,"mtime":1580479372…:1580494995782,"mime":"application/javascript"}↵]", headers: {…}, request: {…}}
console.ts:137 [Extension Host] [  {"name":"app.js","size":325,"mtime":1580479372098,"ctime":1580479372098,"mime":"application/javascript"},  {"name":"router.js","size":341,"mtime":1580502499362,"ctime":1580502499362,"mime":"application/javascript"},  {"name":"server.js","size":64,"mtime":1580494995782,"ctime":1580494995782,"mime":"application/javascript"}]
console.ts:137 [Extension Host] rejected promise not handled within 1 second: ENOENT: no such file or directory, stat '/home/ubuntu/environment/gobarber/src/Teste.js/'
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:196   ERR ENOENT: no such file or directory, stat '/home/ubuntu/environment/gobarber/src/Teste.js/'

console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10039,"seq":20043,"d":["call","ping","ping",["serverTime",{"$":32}]]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20043,"seq":10040,"d":[32,null,{"serverTime":2}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10040,"seq":20044,"d":["stat","/gobarber/src/Testes",{},{"$":91}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20044,"seq":10041,"d":[91,{"stack":"22282: 2069: Error: ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/Testes'\n    at Error (native)","code":"ENOENT","message":"ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/Testes'"}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10041,"seq":20045,"d":["call","ping","ping",["serverTime",{"$":32}]]}

**Comment by igorjunio2015** [comment]
I cleaned up the history and tried to create a new file and a new folder.

File: "Teste.js"
Folder: "Tests"

[error-cloud9-x-vscode.log](https://github.com/iann0036/cloud9-sync/files/4147616/error-cloud9-x-vscode.log)

**Comment by iann0036** [comment]
Thanks for that @igorjunio2015!

I was able to replicate those issues now, looks like there was a fair chunk of functionality that was broken.

I've updated the extension to support the following actions:

VSCode to Cloud9 in Bidirectional mode (filesystem watchers, not initial sync):
* Create a file
* Update a file
* Delete a file
* Create a directory
* Delete a directory (recursive)

Some things that may not work at the moment:
* Some Cloud9 to VSCode actions
* Rename a directory
* Create/update a file/directory where the parent directory structure doesn't exist remotely

Could you test the latest changes in 0.11.1 and let me know if your specific situation improves?

**Comment by igorjunio2015** [comment]
@iann0036 unfortunately did not work. New log follows.

I did:
   1 . I installed the new update (it didn't work)
   2 . I reinstalled the extension (it didn't work)

![image](https://user-images.githubusercontent.com/53827311/73744542-c1e0ed80-472f-11ea-8962-3d2ce80f9f3e.png)

**Comment by iann0036** [comment]
Hi @igorjunio2015,

Apologies, I'm having a hard time replicating your issue. Could you create a new local workspace (empty directory) and follow along with the below video? If you get different results there may be an environment problem or similar I'm missing.

https://www.youtube.com/watch?v=rEF9o9tJR8M

**Comment by igorjunio2015** [comment]
Hi @iann0036 

I recorded a video for you to see, and an error appears.

https://youtu.be/rdSjJtZIhb0

**Comment by iann0036** [comment]
Thanks for that @igorjunio2015!

I totally missed the Resync command in my refactor. I've fixed that up to re-sync based on the chosen sync strategy. I also removed a command to force-reload the workspace after performing the Add To Workspace option - this might improve performance.

I still believe there may be some Windows specific issues I'm missing whilst testing on my Mac so let me know how the latest updates go in 0.11.3

**Comment by igorjunio2015** [comment]
I just tested the improvement but it didn't work for me.

Log follows:

`console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10113,"seq":20100,"d":["stat","/gobarber/src/teste.js",{},{"$":99}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20100,"seq":10114,"d":[99,{"stack":"25072: 3039: Error: ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/teste.js'\n    at Error (native)","code":"ENOENT","message":"ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/teste.js'"}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10114,"seq":20101,"d":["call","ping","ping",["serverTime",{"$":100}]]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20101,"seq":10115,"d":[100,null,{"serverTime":1}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10115,"seq":20102,"d":["stat","/gobarber/src/teste",{},{"$":101}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20102,"seq":10116,"d":[101,{"stack":"25072: 3039: Error: ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/teste'\n    at Error (native)","code":"ENOENT","message":"ENOENT: no such file or directory, lstat '/home/ubuntu/environment/gobarber/src/teste'"}]}`

**Comment by iann0036** [comment]
Thanks @igorjunio2015,

I'm unfortunately still having issues replicating your scenario. Can you provide:

* What's your file/folder structure locally?
* What's the file/folder structure in the environment?
* What's your syncstrategy setting? (None, Download-only or Bidirectional)
* Are you seeing issues on initial connection sync, re-sync or both?
