### ISSUE TITLE
Create more than 1 terminal (not shared)

### ISSUE THREAD

**Issue by igorjunio2015** [iann0036/cloud9-sync#28]
So I'm trying to create 2 terminals through VSCODE but when trying to create a second terminal (not shared) the message appears on the 1st terminal:

![image](https://user-images.githubusercontent.com/53827311/73783451-7bf94900-4772-11ea-914d-55609d942ab1.png)

E o log:
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10205,"seq":20148,"d":["tmux","",{"cwd":"/home/ubuntu/environment","cols":125,"rows":33,"name":"xterm-color","base":"/home/ubuntu/.c9","attach":false,"session":"cloud9_terminal_172","output":false,"terminal":true,"detachOthers":true,"defaultEditor":false,"encoding":"utf8","command":"bash -l"},{"$":90}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10205,"seq":20149,"d":["tmux","",{"cwd":"/home/ubuntu/environment","cols":125,"rows":33,"name":"xterm-color","base":"/home/ubuntu/.c9","attach":false,"session":"cloud9_terminal_263","output":false,"terminal":true,"detachOthers":true,"defaultEditor":false,"encoding":"utf8","command":"bash -l"},{"$":90}]}
console.ts:137 [Extension Host] init'd remote terminal
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20148,"seq":10206,"d":[90,null,{"pty":{"id":22,"readable":true,"writable":true,"pid":10892}}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10206,"seq":20150,"d":["resize",10892,159,33]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10206,"seq":20151,"d":["tmux","",{"capturePane":{"start":-32768,"end":1000,"pane":"cloud9_terminal_263:0.0"},"encoding":"utf8","name":"xterm-color","command":""},{"$":22}]}
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10206,"seq":20152,"d":["write",22,"\u0002:detach -a\n"]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20148,"seq":10207,"d":["onData",22,"\u001b7\u001b[?47h\u001b[m\u001b[?1l\u001b>\u001b[H\u001b[2J\u001b[?1000l\u001b[?1002l\u001b[?1006l\u001b[?1005l\u001b]112\u0007\u001b]0;cloud9_terminal_172:0:export - \"ip-172-31-90-61\" \u0007\u001b[1;1H\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[1;33r\u001b[H"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20148,"seq":10208,"d":["onData",17,"\u001b[H\u001b[32m\u001b[1mubuntu\u001b[m:\u001b[34m\u001b[1m~/environment\u001b[m $ \u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[1;24H"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20149,"seq":10209,"d":[90,null,{"pty":{"id":23,"readable":true,"writable":true,"pid":10971}}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20149,"seq":10210,"d":["onData",23,"\u001b7\u001b[?47h\u001b[m\u001b[?1l\u001b>\u001b[H\u001b[2J\u001b[?1000l\u001b[?1002l\u001b[?1006l\u001b[?1005l\u001b]112\u0007\u001b]0;cloud9_terminal_263:0:export - \"ip-172-31-90-61\" \u0007\u001b[1;1H\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[1;33r\u001b[H"]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20149,"seq":10211,"d":["onData",17,"\u001b[H\u001b[32m\u001b[1mubuntu\u001b[m:\u001b[34m\u001b[1m~/environment\u001b[m $ \u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[1;24H"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20149,"seq":10212,"d":["onData",22,"\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[H"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10213,"d":["onData",22,{"rows":33,"cols":159}]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10214,"d":["onData",22,"\u001b[1;1H\u001b[1;33r\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[H"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10215,"d":[22,null,{"process":{"pid":11020,"stdin":{"id":24,"readable":false,"writable":true},"stdout":{"id":25,"readable":true,"writable":false},"stderr":{"id":26,"readable":true,"writable":false}}}]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10216,"d":["onData",22,"\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[H"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10217,"d":["onData",17,"\u001b[1;33r\u001b[m\u001b[?1l\u001b>\u001b[H\u001b[2J\u001b]112\u0007\u001b[?1000l\u001b[?1002l\u001b[?1006l\u001b[?1005l\u001b[2J\u001b[?47l\u001b8"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10218,"d":["onData",23,"\u001b[1;33r\u001b[m\u001b[?1l\u001b>\u001b[H\u001b[2J\u001b]112\u0007"]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10219,"d":["onData",23,"\u001b[?1000l\u001b[?1002l\u001b[?1006l\u001b[?1005l\u001b[2J\u001b[?47l\u001b8[detached (from session cloud9_terminal_263)]\r\n"]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10220,"d":["onEnd",23,null]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10221,"d":["onData",17,"[detached (from session cloud9_terminal_937)]\r\n"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10222,"d":["onEnd",17,null]}
console.ts:137 [Extension Host] Terminating terminal
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10223,"d":["onProcessClose",10389,null,null]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10224,"d":["onClose",17]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10225,"d":["onExit",10389,0,0]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10226,"d":["onProcessClose",10971,null,null]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10227,"d":["onClose",23]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10228,"d":["onExit",10971,0,0]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10229,"d":["onData",25,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10230,"d":["onEnd",26,null]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10231,"d":["onEnd",25,null]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10232,"d":["onExit",11020,0,null]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10233,"d":["onClose",24]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10234,"d":["onProcessClose",11020,0,null]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10235,"d":["onData",22,"\u001b[32m\u001b[1mubuntu\u001b[m:\u001b[34m\u001b[1m~/environment\u001b[m $ "]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20152,"seq":10236,"d":["onData",22,"\u001b]0;cloud9_terminal_172:0:bash - \"ip-172-31-90-61\" \u0007"]}
console.ts:137 [Extension Host] Emitting terminal data
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 3
console.ts:137 [Extension Host] Sending:
console.ts:137 [Extension Host] 4{"ack":10236,"seq":20153,"d":["call","ping","ping",["serverTime",{"$":32}]]}
console.ts:137 [Extension Host] ---GOT MESSAGE---
console.ts:137 [Extension Host] 4{"ack":20153,"seq":10237,"d":[32,null,{"serverTime":1}]}

**Comment by iann0036** [comment]
Hey @igorjunio2015,

I've done some major changes including aggregating the "shared" terminal functionality for simplicity. This should allow you to create and use more than one terminal at a time _however_ I do see another bug (probably tmux related) that means when adding a new terminal the visibility of the old terminal become hidden, but they are running. If using two at once from that point on is fine though. I'll have to look into that weird bug.

Could you let me know if you can at least get 2 terminals running with 0.11.2?

**Comment by igorjunio2015** [comment]
Good @iann0036 

I tested it here now and it worked to create more than 2 terminals.

I did the test creating 4, and everything went well.

Only the shared terminal that disappeared, but that doesn't interfere with anything working, considering that for me at least it is the need for 2 terminals at the same time.

Thank you very much for your feedback.
