### ISSUE TITLE
I can't use the mouse scroll button on the cloud9 terminal created in VSCODE

### ISSUE THREAD

**Issue by igorjunio2015** [iann0036/cloud9-sync#29]
Hello,
when I try to use the scroll button, (wheel up and down)!

Apparently Wheel up has the function of the up arrow and wheel down with the function of the down arrow.

The following happens:
![image](https://user-images.githubusercontent.com/53827311/73960344-7a05c600-48e9-11ea-84f4-e4a4d771d17e.png)

**Comment by iann0036** [comment]
Cheers @igorjunio2015,

This unfortunately sounds like some nasty issues with winpty as per the referenced:

* https://github.com/microsoft/vscode/issues/29814
* https://github.com/microsoft/vscode/issues/45693

I'll do a bit of research into this but it's likely there won't be an easy solution for this as it's probably upstream.

**Comment by igorjunio2015** [comment]
Hi @iann0036,

Thank you very much for returning my friend!

I hope to contribute a lot to your project ...

Hugs

**Comment by igorjunio2015** [comment]
Hi @iann0036 , I found a solution to use the scroll in the Terminal inside the VSCODE.

Using an alternative terminal Zsh, together with Oh-My-Zsh and Zplugin.

I can use the scroll normally, but with bash it no longer works. And when I'm in the browser inside cloud9, only bash works the scroll and Zsh doesn't ... It's like reversing.

![image](https://user-images.githubusercontent.com/53827311/75554310-d788c080-5a18-11ea-90a8-8935267cab93.png)
