### ISSUE TITLE
Support proxy?

### ISSUE THREAD

**Issue by d0uub** [iann0036/cloud9-sync#3]
i can list environement but cannot connect to cloud9

**Comment by iann0036** [comment]
To confirm, you'd like support for HTTP(S) proxies? If so, I'll add this to the next release.

**Comment by iann0036** [comment]
Hey @d0uub,

Proxy support should now be available. To use, update to 0.9.2+ and add the `cloud9sync.proxy` setting [to your workspace](https://code.visualstudio.com/docs/getstarted/settings) and set it to the format:

```http://1.2.3.4:8888```
or
```http://user:pass@1.2.3.4:8888```

Let me know if that works for you.

**Comment by d0uub** [comment]
it works, thanks!
