### ISSUE TITLE
How to delete C9 Environment?

### ISSUE THREAD

**Issue by i5okie** [iann0036/cloud9-sync#4]
This is a loaded issue uhm.
So looks like you'are creating new environments on the + button. 
I've made a mistake of trying to add an existing one. So now it doesn't work.

Where are these persisted?
I need to delete one of these, and I can't figure out how.
I don't want to destroy it. just remove from the list.

**Comment by iann0036** [comment]
Hi Ivan,

The Cloud9 environments listing is always pulled directly from AWS, so if you see the environment appear in the list it'll have been created and available from the AWS Console.

If you log in to [the Cloud9 console](https://us-west-2.console.aws.amazon.com/cloud9/home) (for the region you specified), you should see all your environments and have the ability to delete any you don't want.

If you actually want to keep this environment but "hide" it from the VS Code listings, the only way currently to do that would be to deny access from the AWS user you associated with in your VS Code settings.

Hope that helps,
Ian.

**Comment by i5okie** [comment]
Ok so yes. I see your intended use. But.
Right after I installed the extension. I clicked + button. It asked for
name of my environment, and then asked for API key, etc etc.
and now when I try to connect to it. It gives me an error saying (will edit
one sec)

**Comment by iann0036** [comment]
Ah, I see.

I believe what is happening is that another user has created the environment and that user has not shared the environment with the user you specified in VS Code. I believe the fix would be to log into the Cloud9 web interface and click the "Share" button and add the user that you're using in VS Code.

Once that is done, you should be able to right-click > Connect to the environment as normal.

Please let me know if this is indeed the issue. If so, I'll update the error message and documentation to make this a little more clear.

**Comment by i5okie** [comment]
Yep, you're right. weird.
I'm logged in to c9 with cross account role... i don't understand how im authenticated on c9 then. because I am using the credentia..... aaah. i see now.

Yep, great its working now. thank you!
