### ISSUE TITLE
Cannot connect to environment

### ISSUE THREAD

**Issue by NikolaBravo** [iann0036/cloud9-sync#8]
Hi,

Once initial setup is completed, environment does not show up, IAM User has attached AWSCloud9Administrator IAM policy, SG on Cloud9 EC2 instance has necessary roles to allow all traffic, refreshing the environment does not change much, uninstall and reinstall didn't helped....

Please advise if i have missed something? 

Thanks,
Nikola Bravo

**Comment by iann0036** [comment]
Hi Nikola,

Thanks for reaching out. Could you open Tools > Toggle Developer Tools and ensure the Console tab is selected. From there, could you please report any messages you receive from Extension Host (especially any that are red)? You may have to expand some Object messages to see the full information.

Please also ensure to remove any identifying information before posting, or alternatively you could send to me directly at cloud9sync@ianmckay.com.au

**Comment by NikolaBravo** [comment]
Hi Ian,

Resolved, it was AssumeRole issue in VSCode, thank you sir!
